### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by davidjun3** [JonnoFTW/traffic-prediction#3]
when i running the python main.py 1 some.csv
The IDE tell me TypeError: minimize() got an unexpected keyword argument 'extra'
How can I deal with this problem?

**Comment by davidjun3** [comment]
I have defined the Parameters in extra.
steps=1 like in readme.md
file_path='some.csv' a csv file in the same directory.

**Comment by JonnoFTW** [comment]
I made some modifications to the original hyperas script. They're in my fork here:

https://github.com/JonnoFTW/hyperas

This branch is not up to date with the main hyperas package though. If you really want to use my script, you need to install hyperas from my fork.

**Comment by davidjun3** [comment]
Thank you very much

**Comment by davidjun3** [comment]
Using your hyperas has handled that problem,But I meet another problem,which says:
fmin() got an unexpected keyword argument 'rseed'
Can you tell me the whole python environment of your script?
I really really want to use your script to do some research.

**Comment by davidjun3** [comment]
The error messages is 
Traceback (most recent call last):
  File "/home/ending/LSTM/JonnoFTW(LSTM)/traffic-prediction-master/main.py", line 149, in <module>
    extra={'steps': steps, 'FPATH': file_path}
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed, extra=extra)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 118, in base_minimizer
    rseed=rseed)
TypeError: fmin() got an unexpected keyword argument 'rseed'

Is it also result by hyperas?

**Comment by davidjun3** [comment]
I have run the script successfully, thank you so much

**Comment by SmatterTalk** [comment]
How to solve the error  `TypeError: fmin() got an unexpected keyword argument 'rseed'` ?

**Comment by SmatterTalk** [comment]
I 've meet the same error like above
```
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    extra={'steps': steps, 'FPATH': file_path}
  File "/Users/wuyao/anaconda2/envs/python2/lib/python2.7/site-packages/hyperas/optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed, extra=extra)
  File "/Users/wuyao/anaconda2/envs/python2/lib/python2.7/site-packages/hyperas/optim.py", line 118, in base_minimizer
    rseed=rseed)
TypeError: fmin() got an unexpected keyword argument 'rseed'
```

could you tell me how to solve this problem?

Thanks~!
